---
  - name: Installing and launch Metricbeat
    hosts: webservers
    become: yes
    tasks:
    # Use command module
    - name: Download filebeat .deb filebeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    # Use command module
    - name: Install filebeat .deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    # Use copy module
    - name: Drop in metricbeat.yml
      copy: 
        src: /etc/ansible/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    # Use command module 
    - name: Enable and configure system module
      command: metricbeat modules enable system

    # Use command module 
    - name: Setup metricbeat
      command: metricbeat setup

    # Use command module
    - name: Start metricbeat service
      command: service metricbeat start

    # Use systemd module
    - name: Enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes 